In [1]:
from dgbg import dgbg
import numpy as np

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

In [2]:
box = dgbg.binding_box('pdb_files/1a52.pdb')

In [3]:
ligand_data = box.get_ligand_data('EST', 'A')

In [5]:
ligand_data

,TYPE,SERIAL_NUM,ELEMENT,AA,CHAIN_ID,RESIDUE_NUM,X_COOR,Y_COOR,Z_COOR,OCCUPANCY,TEMP_FACTOR,ELEMENT
3825,HETATM,3828,C1,EST,A,1,107.008,15.860,99.456,1.00,45.94,C
3826,HETATM,3829,C2,EST,A,1,106.932,16.930,100.366,1.00,45.69,C
3827,HETATM,3830,C3,EST,A,1,106.833,18.229,99.892,1.00,46.02,C
3828,HETATM,3831,O3,EST,A,1,106.801,19.239,100.813,1.00,46.45,O
3829,HETATM,3832,C4,EST,A,1,106.793,18.503,98.487,1.00,46.12,C
3830,HETATM,3833,C5,EST,A,1,106.876,17.424,97.544,1.00,46.33,C
3831,HETATM,3834,C6,EST,A,1,106.938,17.714,96.043,1.00,46.47,C
3832,HETATM,3835,C7,EST,A,1,107.309,16.503,95.165,1.00,46.66,C
3833,HETATM,3836,C8,EST,A,1,106.672,15.191,95.681,1.00,45.82,C
3834,HETATM,3837,C9,EST,A,1,107.190,14.870,97.123,1.00,44.99,C
3835,HETATM,3838,C10,EST,A,1,106.998,16.065,98.050,1.00,45.58,C
3836,HETATM,3839,C11,EST,A,1,106.590,13.552,97.642,1.00,45.46,C
3837,HETATM,3840,C12,EST,A,1,106.782,12.364,96.667,1.00,45.93,C
3838,HETATM,3841,C13,EST,A,1,106.322,12.668,95.240,1.00,46.73,C
3839,HETATM,3842,C14,EST,A,1,107.020,13.991,94.766,1.00,46.06,C
3840,HETATM,3843,C15,EST,A,1,106.743,14.016,93.262,1.00,46.15,C
3841,HETATM,3844,C16,EST,A,1,106.965,12.544,92.837,1.00,47.09,C
3842,HETATM,3845,C17,EST,A,1,106.876,11.691,94.171,1.00,47.06,C
3843,HETATM,3846,O17,EST,A,1,106.197,10.417,93.968,1.00,47.62,O
3844,HETATM,3847,C18,EST,A,1,104.760,12.691,95.140,1.00,47.31,C

In [6]:
centroid, box_size = box.create_box(spacing=0.375, padding=np.array([0, 0, 0]))

In [7]:
box_size

array([ 6., 23., 21.])

In [8]:
centroid

array([106.73025,  15.0231 ,  96.61565])

In [9]:
result = box.show_result(centroid, box_size)

In [10]:
result

NGLWidget()